server:
  port: 8080
  servlet:
    context-path: /identity
spring:
  application:
    name: booking-train-backend
  datasource:
    url: "jdbc:mysql://localhost:3306/booking-train"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/booking
idp:
  url: http://localhost:8081
  client-id: client_Id
  client-secret: Client-secret