server:
  port: 8080

spring:
  profiles:
    active: dev
  application:
    name: booking-train-backend
  redis:
    host: localhost
    port: 6379
  datasource:
    url: jdbc:mysql://localhost:3306/Booking_Train
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${ISSUER_URI}
  mail:
    host: smtp.gmail.com
    port: 587
    username:
    password:
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
    from: Tamn0443@gmail.com



bucket4j:
  enabled: true
  filters:
    - cache-name: localCache
      url: /api/auth/login
      rate-limits:
        - bandwidths:
            - capacity: 5
              refill-tokens: 5
              refill-period: 10
              refill-unit: seconds
    - cache-name: localCache
      url: /api/auth/refresh
      rate-limits:
        - bandwidths:
            - capacity: 5
              refill-tokens: 5
              refill-period: 10
              refill-unit: seconds

idp:
  url: http://localhost:8081
  client-id: ${IDP_CLIENT_ID}
  client-secret: ${IDP_CLIENT_SECRET}
  realm: ${IDP_REALM}
  google-redirect-uri: http://localhost:5173/oauth2/callback

#Config Qr
Qr:
   width: 300
   height: 300

#Config Payment
payment:
  vnp_TmnCode:
  vnp_HashSecret:
  vnp_Url: "https://sandbox.vnpayment.vn/paymentv2/vpcpay.html"
  returnUrl : "https://your-domain.com/vnpay-return"


springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui
    operationsSorter: method
    tagsSorter: alpha

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.validation: DEBUG

