server:
  port: 8080

spring:
  application:
    name: booking-train-backend
  redis:
    host: localhost
    port: 6379
  datasource:
    url: jdbc:mysql://localhost:3306/Booking_Train
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/booking
  mail:
    host: smtp.gmail.com
    port: 587
    username: your.email@gmail.com
    password: your-app-password
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
    from: Tamn0443@gmail.com



bucket4j:
  enabled: true
  filters:
    - cache-name: localCache
      url: /api/auth/login
      rate-limits:
        - bandwidths:
            - capacity: 5
              refill-tokens: 5
              refill-period: 10
              refill-unit: seconds
    - cache-name: localCache
      url: /api/auth/refresh
      rate-limits:
        - bandwidths:
            - capacity: 5
              refill-tokens: 5
              refill-period: 10
              refill-unit: seconds

idp:
  url: http://localhost:8081
  client-id: client_Id
  client-secret: Client-secret
  realm: security-keycloak

#Config Qr
Qr:
   width: 300
   height: 300

